#############################################################################
# Makefile for building: all
# Generated by qmake (2.01a) (Qt 4.8.7) on: Thu Jun 30 10:41:05 2016
# Project:  all.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile all.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-pointing \
		sub-apps

pointing//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) pointing/ || $(MKDIR) pointing/ 
	cd pointing/ && $(QMAKE) /media/vvkdhkl/New\ Volume/vvkdhkl-pointingexp-1433e939ccd6/pointing/pointing.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 -o $(MAKEFILE)
sub-pointing-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) pointing/ || $(MKDIR) pointing/ 
	cd pointing/ && $(QMAKE) /media/vvkdhkl/New\ Volume/vvkdhkl-pointingexp-1433e939ccd6/pointing/pointing.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 -o $(MAKEFILE)
sub-pointing: pointing//$(MAKEFILE) FORCE
	cd pointing/ && $(MAKE) -f $(MAKEFILE)
sub-pointing-make_default: pointing//$(MAKEFILE) FORCE
	cd pointing/ && $(MAKE) -f $(MAKEFILE) 
sub-pointing-make_first: pointing//$(MAKEFILE) FORCE
	cd pointing/ && $(MAKE) -f $(MAKEFILE) first
sub-pointing-all: pointing//$(MAKEFILE) FORCE
	cd pointing/ && $(MAKE) -f $(MAKEFILE) all
sub-pointing-clean: pointing//$(MAKEFILE) FORCE
	cd pointing/ && $(MAKE) -f $(MAKEFILE) clean
sub-pointing-distclean: pointing//$(MAKEFILE) FORCE
	cd pointing/ && $(MAKE) -f $(MAKEFILE) distclean
sub-pointing-install_subtargets: pointing//$(MAKEFILE) FORCE
	cd pointing/ && $(MAKE) -f $(MAKEFILE) install
sub-pointing-uninstall_subtargets: pointing//$(MAKEFILE) FORCE
	cd pointing/ && $(MAKE) -f $(MAKEFILE) uninstall
apps//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) apps/ || $(MKDIR) apps/ 
	cd apps/ && $(QMAKE) /media/vvkdhkl/New\ Volume/vvkdhkl-pointingexp-1433e939ccd6/apps/apps.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 -o $(MAKEFILE)
sub-apps-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) apps/ || $(MKDIR) apps/ 
	cd apps/ && $(QMAKE) /media/vvkdhkl/New\ Volume/vvkdhkl-pointingexp-1433e939ccd6/apps/apps.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 -o $(MAKEFILE)
sub-apps: apps//$(MAKEFILE) FORCE
	cd apps/ && $(MAKE) -f $(MAKEFILE)
sub-apps-make_default: apps//$(MAKEFILE) FORCE
	cd apps/ && $(MAKE) -f $(MAKEFILE) 
sub-apps-make_first: apps//$(MAKEFILE) FORCE
	cd apps/ && $(MAKE) -f $(MAKEFILE) first
sub-apps-all: apps//$(MAKEFILE) FORCE
	cd apps/ && $(MAKE) -f $(MAKEFILE) all
sub-apps-clean: apps//$(MAKEFILE) FORCE
	cd apps/ && $(MAKE) -f $(MAKEFILE) clean
sub-apps-distclean: apps//$(MAKEFILE) FORCE
	cd apps/ && $(MAKE) -f $(MAKEFILE) distclean
sub-apps-install_subtargets: apps//$(MAKEFILE) FORCE
	cd apps/ && $(MAKE) -f $(MAKEFILE) install
sub-apps-uninstall_subtargets: apps//$(MAKEFILE) FORCE
	cd apps/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: all.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile all.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile all.pro

qmake_all: sub-pointing-qmake_all sub-apps-qmake_all FORCE

make_default: sub-pointing-make_default sub-apps-make_default FORCE
make_first: sub-pointing-make_first sub-apps-make_first FORCE
all: sub-pointing-all sub-apps-all FORCE
clean: sub-pointing-clean sub-apps-clean FORCE
distclean: sub-pointing-distclean sub-apps-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-pointing-install_subtargets sub-apps-install_subtargets FORCE
uninstall_subtargets: sub-pointing-uninstall_subtargets sub-apps-uninstall_subtargets FORCE

sub-pointing-check: pointing/$(MAKEFILE)
	cd pointing/ && $(MAKE) -f $(MAKEFILE) check
sub-apps-check: apps/$(MAKEFILE)
	cd apps/ && $(MAKE) -f $(MAKEFILE) check
check: sub-pointing-check sub-apps-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

